# Generated by Django 4.2.13 on 2024-05-29 15:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LevelOfDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('ref_id', models.CharField(max_length=32)),
                ('level_of_description', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordkeeper.levelofdescription')),
            ],
        ),
    ]
